// Generated by CoffeeScript 1.9.2
module.exports = function(range) {
  var zooms;
  zooms = [];
  return function(zoom) {
    var averaged, i, j, langolier, len, now, total, z;
    now = new Date().getTime();
    langolier = 0;
    total = zoom;
    for (i = j = 0, len = zooms.length; j < len; i = ++j) {
      z = zooms[i];
      if (z.t < now - range) {
        langolier = i;
      } else {
        total += z.z;
      }
    }
    zooms.splice(0, langolier);
    if (zooms.length > 0) {
      averaged = Math.floor(total / zooms.length);
      zoom = Math.max(zoom - 1, Math.min(zoom + 1, averaged));
    }
    zooms.push({
      t: now,
      z: zoom
    });
    return zoom;
  };
};
